### ISSUE TITLE
Need to return the same information when requesting a Raw-Capture by Id

### ISSUE THREAD

**Issue by gwynndp** [Greenstand/treetracker-field-data#85]
When loading the Capture Detail view we make a request to the `raw-captures/:id` endpoint and it doesn't return the `wallet` field.

Please see this issue for reference: https://github.com/Greenstand/treetracker-admin-client/issues/938

**Comment by Kpoke** [comment]
@gwynndp confirmed that the API is returning the wallet field on both occasions.

**Comment by Kpoke** [comment]
@gwynndp confirmed that the API is returning the wallet field on both occasions.
